name: Build and push Docker image

on:
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "SHA=$SHA" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: |
          docker build -t alan01777/semana-nacional-ti:${{ steps.generate_sha.outputs.sha }} -f .docker/docker_images/dockerfile.laravel .

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          docker push alan01777/semana-nacional-ti:${{ steps.generate_sha.outputs.sha }}
          docker tag alan01777/semana-nacional-ti:${{ steps.generate_sha.outputs.sha }} alan01777/semana-nacional-ti:latest
          docker push alan01777/semana-nacional-ti:latest
