name: Run tests

on: [push, pull_request]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: .github/workflows/setup-php.yml
      - uses: .github/workflows/run-tests.yml
      - uses: .github/workflows/generate-sha.yml
      - uses: .github/workflows/build-docker-image.yml
      - uses: .github/workflows/push-image.yml
