name: Run tests

on: [push, pull_request]

jobs:
  setup:
    name: Setup environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: php artisan test

  build-docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate sha
        id: generate_sha
        run: echo "::set-output name=sha::$(echo $GITHUB_SHA | head -c7)"

      - name: Build docker image
        run: docker build -t alan01777/semana-nacional-ti:${{ needs.build-docker.outputs.sha }} -f .docker/docker_images/dockerfile.laravel .

  push-image:
    name: Push Docker image
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          docker push alan01777/semana-nacional-ti:${{ needs.build-docker.outputs.sha }}
          docker tag alan01777/semana-nacional-ti:${{ needs.build-docker.outputs.sha }} alan01777/semana-nacional-ti:latest
          docker push alan01777/semana-nacional-ti:latest
