name: Push Image

on:
  push:
    branches:
      - main

jobs:
  push-image:
    name: Push image
    runs-on: ubuntu-latest
    needs: generate-sha
    steps:
      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          docker push alan01777/semana-nacional-ti:${{ needs.generate-sha.outputs.sha }}
          docker tag alan01777/semana-nacional-ti:${{ needs.generate-sha.outputs.sha }} alan01777/semana-nacional-ti:latest
          docker push alan01777/semana-nacional-ti:latest
