name: Push Image

on:
  workflow_dispatch:

jobs:
  push-image:
    name: Push image
    runs-on: ubuntu-latest
    steps:
      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "SHA=$SHA" >> $GITHUB_OUTPUT

      - name: Push image
        run: |
          docker push alan01777/semana-nacional-ti:${{ steps.generate_sha.outputs.sha }}
          docker tag alan01777/semana-nacional-ti:${{ steps.generate_sha.outputs.sha }} alan01777/semana-nacional-ti:latest
          docker push alan01777/semana-nacional-ti:latest
